### ISSUE TITLE
Issue templates for this repo

### ISSUE THREAD

**Issue by Ayush0431** [jina-ai/good-first-issues#14]
Check the insights and complete all the necessary items  for this repo.

**Comment by ayushi424** [comment]
Hi, I am Ayushi, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you.

**Comment by Ayush0431** [comment]
Go ahead it's all yours

**Comment by ayushi424** [comment]
Thankyou @Ayush0431.  
Could you please assign this issue to me so that I can make a PR asap.
@alexcg1

**Comment by ayushi424** [comment]
Hi @alexcg1, I could see that this repo already has bug_report.md and feature_request.md templates that could be used as Issue Templates.
So is this issue workable ?

**Comment by alexcg1** [comment]
Hmmm....I guess not. Seems one of our team already did it. We're open to other contributions though!

I'll close this since it's already been done
